version: '3.8'

services:
  dev:  # local db
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    env_file:
      - .env.dev  # see .env.template
    environment:
      MONGO_URL: mongodb://root_user:root_password@db:27017
      MONGO_DB: dev
      TEST_MONGO_DB: dev_test
    depends_on:
      - db
    networks:
      - backend_network
    volumes:
      - .:/project
    ports:
      - 8080:8080

  dev_remote:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    env_file:
      - .env.dev_remote  # see .env.template
    environment:
      MONGO_DB: dev
      TEST_MONGO_DB: dev_test
    volumes:
      - .:/project
    ports:
      - 8080:8080

  db:
    image: mongo:6.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: root_user
      MONGO_INITDB_ROOT_PASSWORD: root_password
      MONGO_INITDB_DATABASE: sample
    ports:
      - 27017:27017
    networks:
      - backend_network
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:

networks:
 backend_network:
