FROM python:3.10-bullseye

ENV PYTHONUNBUFFERED 1
ENV QTWEBENGINE_CHROMIUM_FLAGS="--no-sandbox"

# Install calibre for ebook-convert command
RUN apt-get update && apt-get install -y \
    libegl1 \
    libopengl0 \
    libegl1 \
    libopengl0 \
    libxkbcommon0 \
    libglx0 \
    libnss3 \
    libxcomposite1 \
    libxrandr2 \
    libxkbfile1 \
    libxtst6 \
    ffmpeg

RUN wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh \
    | sh /dev/stdin install_dir=/opt isolated=y

# Install the project's pip dependencies
WORKDIR /project
COPY ./requirements-dev.txt ./

ENV PYTHONPATH "${PYTHONPATH}:/project"

RUN pip3 --disable-pip-version-check install -r requirements-dev.txt

# copy the entire project
COPY ./ ./

# Run server
CMD make start-dev
